movies = ["ae dil hai mushkil","black panther","avatar","action","doctor strange","sucide squad","avengers infinity war","captain marvel",
"avengers endgame","garam masala","aashiqi","hera pheri","awara paagal deewana","spiderman","deadpool","spiderman 2","deadpool 2",
"phir hera pheri","aashiqi 2","antman","thor","antman and the wasp","run","agnipath","bang bang","bad boys","captain america","blue",
"big hero","thor the dark world","big brother","chhichhore","jumanji the next level","chennai vs china","sanam teri kasam",
"chandini chowk to china","parasite","chak de india","wanted","dabbang","tubelight","shivay","dhrishyam","chennai express","36 china town","soorma",
"drunken master","baaghi 3","dhoom","gaurdians of the galaxy","dhoom 2","spiderman noway home","dhoom 3","dhishoom","captain america civil war",
"don2","black water","baby","terenaam","dabbang2","scam1992","abcd","deewana","don","jumanji","roohi","bell botom","kingkong","venom",
"dear comrade","gaurdians of the galaxy vol 3","kanchana","abcd 2","kanchana returns","raaz","raaz reboot","dil bechara","3 idiots","kedaranath",
"ek tha tiger","fukrey","baaghi2","fukreyreturns","faltu","golmaal","spiderman","golmaal fun unlimited","spiderman 3","golmaal returns","golmaal 3",
"thetomorrow war","tik tik tik","robot","the avengers","spiderman homecomming","ironman 3","loki","falcon and the wintersoldier","thor ragnarok"
"the maze runner","sarrainodu","surya the soldier","dream girl","kabir singh","sheershah","radhe","klaus","bhuj the pride of india","monkey king",
"frozen","vicky donor","world war z","good newzz","johnwick","gully boy","uri","traintobusan","khatarnakkhiladi","commando","commando 2","commando 3",
"sonu ke titu ki sweety","anaconda","the meg","iron man","iron man 2","gaurdians of the galaxy vol 2","journey to the west","mortal kombat","kingsmen",
"baaghi","the flying jatt","terminator","resident evil","titanic","the lord of the rings","sanju","kai p oche","shaadi mai zaroor aana","godzilla",
"war","the incredible hulk","avengers age of ultron","black widow","the real jackpot","lagaan","sooryavansham","bhootnath","nayak","tarzan the he man",
"tarzan the wonder car","logan","wolverine","lucifer","holiday","wanda vision","pk","rustom","rowdy rathore","student of the year","wednesday",
"mission mangal","paltan","tumbbad","badlapur","badrinath ki dulhaniya","main tera hero","marjaavan","pati patni aur woh","lukka chuppi","joker","extraction",
"conjuring","bahubali the beginning","bahubali the conclusion","over the moon","ip man","singham","sholay","singham returns","batti gul meter chalu",
"dhadak","border","vedalam","tadaka","stree","taare zameen par","world famous lover","agent sai","geeta govinda","after","toy story","roohi","businessman 2",
"no 1 businessman","the amazing spiderman","the amazing spiderman 2","ready"]